-- GENERATED by tools/gen-migration.mjs from www/sqlite-adapter.js SCHEMA. Do not edit by hand.
CREATE TABLE IF NOT EXISTS "settings" (
  "key" TEXT PRIMARY KEY NOT NULL,
  data TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE IF NOT EXISTS "products" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ix_name",
  "ix_category",
  data TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS "idx_products_name" ON "products"("ix_name");
CREATE INDEX IF NOT EXISTS "idx_products_category" ON "products"("ix_category");
CREATE TABLE IF NOT EXISTS "bills" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ix_date",
  "ix_customerId",
  data TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS "idx_bills_date" ON "bills"("ix_date");
CREATE INDEX IF NOT EXISTS "idx_bills_customerId" ON "bills"("ix_customerId");
CREATE TABLE IF NOT EXISTS "customers" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ix_name",
  "ix_phone",
  data TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS "idx_customers_name" ON "customers"("ix_name");
CREATE INDEX IF NOT EXISTS "idx_customers_phone" ON "customers"("ix_phone");
CREATE TABLE IF NOT EXISTS "suppliers" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ix_name",
  data TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS "idx_suppliers_name" ON "suppliers"("ix_name");
CREATE TABLE IF NOT EXISTS "requirements" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ix_status",
  "ix_reminderDate",
  data TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS "idx_requirements_status" ON "requirements"("ix_status");
CREATE INDEX IF NOT EXISTS "idx_requirements_reminderDate" ON "requirements"("ix_reminderDate");
CREATE TABLE IF NOT EXISTS "returns" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ix_billId",
  "ix_date",
  data TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS "idx_returns_billId" ON "returns"("ix_billId");
CREATE INDEX IF NOT EXISTS "idx_returns_date" ON "returns"("ix_date");
CREATE TABLE IF NOT EXISTS "alterations" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ix_status",
  "ix_expectedDate",
  data TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS "idx_alterations_status" ON "alterations"("ix_status");
CREATE INDEX IF NOT EXISTS "idx_alterations_expectedDate" ON "alterations"("ix_expectedDate");
CREATE TABLE IF NOT EXISTS "attendance" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ix_staffKey",
  "ix_date",
  data TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS "idx_attendance_staffKey" ON "attendance"("ix_staffKey");
CREATE INDEX IF NOT EXISTS "idx_attendance_date" ON "attendance"("ix_date");
CREATE TABLE IF NOT EXISTS "stockAdjustments" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ix_productId",
  "ix_date",
  data TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS "idx_stockAdjustments_productId" ON "stockAdjustments"("ix_productId");
CREATE INDEX IF NOT EXISTS "idx_stockAdjustments_date" ON "stockAdjustments"("ix_date");
CREATE TABLE IF NOT EXISTS "purchaseOrders" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ix_supplierId",
  "ix_status",
  data TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS "idx_purchaseOrders_supplierId" ON "purchaseOrders"("ix_supplierId");
CREATE INDEX IF NOT EXISTS "idx_purchaseOrders_status" ON "purchaseOrders"("ix_status");
CREATE TABLE IF NOT EXISTS "purchaseInvoices" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ix_supplierId",
  "ix_date",
  data TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS "idx_purchaseInvoices_supplierId" ON "purchaseInvoices"("ix_supplierId");
CREATE INDEX IF NOT EXISTS "idx_purchaseInvoices_date" ON "purchaseInvoices"("ix_date");
CREATE TABLE IF NOT EXISTS "purchaseReturns" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ix_supplierId",
  "ix_date",
  data TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS "idx_purchaseReturns_supplierId" ON "purchaseReturns"("ix_supplierId");
CREATE INDEX IF NOT EXISTS "idx_purchaseReturns_date" ON "purchaseReturns"("ix_date");
CREATE TABLE IF NOT EXISTS "purchasePriceHistory" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ix_productId",
  "ix_date",
  data TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS "idx_purchasePriceHistory_productId" ON "purchasePriceHistory"("ix_productId");
CREATE INDEX IF NOT EXISTS "idx_purchasePriceHistory_date" ON "purchasePriceHistory"("ix_date");
CREATE TABLE IF NOT EXISTS "quotations" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ix_customerId",
  "ix_date",
  data TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS "idx_quotations_customerId" ON "quotations"("ix_customerId");
CREATE INDEX IF NOT EXISTS "idx_quotations_date" ON "quotations"("ix_date");
CREATE TABLE IF NOT EXISTS "bookings" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ix_customerId",
  "ix_status",
  "ix_date",
  data TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS "idx_bookings_customerId" ON "bookings"("ix_customerId");
CREATE INDEX IF NOT EXISTS "idx_bookings_status" ON "bookings"("ix_status");
CREATE INDEX IF NOT EXISTS "idx_bookings_date" ON "bookings"("ix_date");
CREATE TABLE IF NOT EXISTS "coupons" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ix_code",
  data TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS "idx_coupons_code" ON "coupons"("ix_code");
CREATE TABLE IF NOT EXISTS "expenses" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ix_date",
  "ix_category",
  data TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS "idx_expenses_date" ON "expenses"("ix_date");
CREATE INDEX IF NOT EXISTS "idx_expenses_category" ON "expenses"("ix_category");
CREATE TABLE IF NOT EXISTS "firms" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ix_name",
  data TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS "idx_firms_name" ON "firms"("ix_name");
CREATE TABLE IF NOT EXISTS "stockTransfers" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ix_date",
  "ix_fromFirmId",
  "ix_toFirmId",
  data TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS "idx_stockTransfers_date" ON "stockTransfers"("ix_date");
CREATE INDEX IF NOT EXISTS "idx_stockTransfers_fromFirmId" ON "stockTransfers"("ix_fromFirmId");
CREATE INDEX IF NOT EXISTS "idx_stockTransfers_toFirmId" ON "stockTransfers"("ix_toFirmId");
CREATE TABLE IF NOT EXISTS "dayCloses" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ix_date",
  "ix_firmId",
  data TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS "idx_dayCloses_date" ON "dayCloses"("ix_date");
CREATE INDEX IF NOT EXISTS "idx_dayCloses_firmId" ON "dayCloses"("ix_firmId");
CREATE TABLE IF NOT EXISTS "openBills" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "ix_firmId",
  data TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS "idx_openBills_firmId" ON "openBills"("ix_firmId");
